# Generated by Django 3.2.4 on 2021-06-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_sets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='transcription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='reters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evaluations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.IntegerField(choices=[(0, 'clearvoice'), (1, 'sound_repetition'), (2, 'word_repetition'), (3, 'phrase_repetition'), (4, 'interjection'), (5, 'prolongation'), (6, 'block'), (7, 'part_word_repetition')], default=0)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.clips')),
                ('rater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.reters')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.transcription')),
            ],
        ),
        migrations.AddField(
            model_name='clips',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.data_sets'),
        ),
        migrations.AddField(
            model_name='clips',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.transcription'),
        ),
    ]
